additionalRepositories:
  - url: https://github.com/JohannesKonings/aws-cdk
    checkoutLocation: aws-cdk

tasks:
  - name: aws-cdk
    before: |
      cd ../aws-cdk
    init: |
      cat README.md
    #   echo npm run build
    command: |
      cat README.md